/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.form;

import dao.NhanVienDao;
import connectDB.ConnectDB;
import entity.LoaiNhanVien;
import entity.NhanVien;
import entity.TaiKhoan;
import gui.swing.JPanerRadiusBorder;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class Form_NhanVien extends javax.swing.JPanel {
    private NhanVien nv;
    private NhanVienDao nvdao;
    private DefaultTableModel modalNhanVien;
     private Form_Register form_register;
  
    

    /**
     * Creates new form frm_QuanLyNhanVien
     */
    public Form_NhanVien() {
         modalNhanVien=new DefaultTableModel();
         nvdao=new NhanVienDao();
        
        initComponents();
        docDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        TextDiaChi = new javax.swing.JTextField();
        cmbTrangThaiLamViec = new javax.swing.JComboBox<>();
        cmbLoaiNhanVien = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        checkBoxGioiTinh = new javax.swing.JCheckBox();
        TextNgaySinh = new com.toedter.calendar.JDateChooser();
        MaNhanVien = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbTimTrangThaiLamViec = new javax.swing.JComboBox<>();
        cmbTimLoaiNhanVien = new javax.swing.JComboBox<>();
        LocNhanVine = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhanVien = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jButton3TimTheoTen = new javax.swing.JButton();
        jbuttonThemNhanVien = new javax.swing.JButton();
        jButton2UpdateNhanVien = new javax.swing.JButton();
        JbuttonLamMoi = new javax.swing.JButton();
        jButton10deleteNhanVien = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(242, 240, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(121, 87, 142))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(124, 36, 207));
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Tên nhân viên:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Mã nhân viên:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Địa chỉ:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Số điện thoại:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Giới tính:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Loại nhân viên:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Trạng thái làm việc:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Số CMND/CCCD:");

        txtTenNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtCCCD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        TextDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        cmbTrangThaiLamViec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbTrangThaiLamViec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm", "Đã nghỉ" }));

        cmbLoaiNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Ngày sinh:");

        checkBoxGioiTinh.setText("Nữ");

        MaNhanVien.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel5))
                        .addGap(66, 66, 66)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextDiaChi)
                            .addComponent(TextNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNhanVien)
                            .addComponent(txtSDT)
                            .addComponent(txtCCCD, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbLoaiNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTrangThaiLamViec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxGioiTinh)
                                    .addComponent(MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(checkBoxGioiTinh))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbLoaiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTrangThaiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(TextNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(242, 240, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(121, 87, 142))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(124, 36, 207));
        jPanel3.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Loại nhân viên:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Trạng thái làm việc:");

        cmbTimTrangThaiLamViec.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbTimTrangThaiLamViec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm", "Nghỉ viêc", " ", " " }));

        cmbTimLoaiNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        LocNhanVine.setBackground(new java.awt.Color(177, 100, 252));
        LocNhanVine.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LocNhanVine.setForeground(new java.awt.Color(255, 255, 255));
        LocNhanVine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/filter.png"))); // NOI18N
        LocNhanVine.setText("Lọc");
        LocNhanVine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocNhanVineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(38, 38, 38)
                                .addComponent(cmbTimLoaiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTimTrangThaiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(LocNhanVine, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbTimLoaiNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(cmbTimTrangThaiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(LocNhanVine, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        jLabel17.setBackground(new java.awt.Color(121, 87, 142));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(121, 87, 142));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img/nhanVien.png"))); // NOI18N
        jLabel17.setText("Quản lí nhân viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE)
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(121, 87, 142))); // NOI18N

        jTableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Giới tính", "Số điện thoại", "Địa chỉ", "Ngày sinh ", "CCCD", "Loại nhân viên", "Trạng thái làm việc"
            }
        ));
        jTableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNhanVien);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(121, 87, 142))); // NOI18N

        jButton3TimTheoTen.setBackground(new java.awt.Color(177, 100, 252));
        jButton3TimTheoTen.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3TimTheoTen.setForeground(new java.awt.Color(255, 255, 255));
        jButton3TimTheoTen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/search.png"))); // NOI18N
        jButton3TimTheoTen.setText("Tìm");
        jButton3TimTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3TimTheoTenActionPerformed(evt);
            }
        });

        jbuttonThemNhanVien.setBackground(new java.awt.Color(177, 100, 252));
        jbuttonThemNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbuttonThemNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonThemNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/buy-online.png"))); // NOI18N
        jbuttonThemNhanVien.setText("Thêm");
        jbuttonThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonThemNhanVienActionPerformed(evt);
            }
        });

        jButton2UpdateNhanVien.setBackground(new java.awt.Color(177, 100, 252));
        jButton2UpdateNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2UpdateNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jButton2UpdateNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/edit.png"))); // NOI18N
        jButton2UpdateNhanVien.setText("Sửa");
        jButton2UpdateNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2UpdateNhanVienActionPerformed(evt);
            }
        });

        JbuttonLamMoi.setBackground(new java.awt.Color(177, 100, 252));
        JbuttonLamMoi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JbuttonLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        JbuttonLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/reset.png"))); // NOI18N
        JbuttonLamMoi.setText("Làm mới");
        JbuttonLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonLamMoiActionPerformed(evt);
            }
        });

        jButton10deleteNhanVien.setBackground(new java.awt.Color(177, 100, 252));
        jButton10deleteNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton10deleteNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jButton10deleteNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/huyPhongCho.png"))); // NOI18N
        jButton10deleteNhanVien.setText("Xóa");
        jButton10deleteNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10deleteNhanVienActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(177, 100, 252));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/taoTk.png"))); // NOI18N
        jButton9.setText("Tạo tài khoản");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2UpdateNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3TimTheoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JbuttonLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbuttonThemNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jButton10deleteNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3TimTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2UpdateNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbuttonLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10deleteNhanVien)
                    .addComponent(jButton9))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void docDuLieu(){
        
         
        nvdao=new NhanVienDao();
        modalNhanVien=(DefaultTableModel) jTableNhanVien.getModel();
        MaNhanVien.setText(nvdao.TaoSoNgauNhien());
        ArrayList<NhanVien> dsNhanVien=nvdao.getAllNhanVien();
        for(NhanVien nv:dsNhanVien){        
            modalNhanVien.addRow(new Object[]{nv.getMaNhanVien(),nv.getTenNhanVien(),nv.getGioiTinh()==true?"Nữ":"Nam",nv.getSoDienThoai(),nv.getDiaChi(),nv.getNgaySinh(),nv.getCCCD(),nv.getLnv().getTenLoaiNhanVien(),nv.getTrangThaiLamViec()? "Đang làm" : "Đã nghỉ" });    
        }
      ArrayList<LoaiNhanVien> dsLoaiNhanVien=nvdao.getAllLoaiNhanVien();
       for(LoaiNhanVien lnv:dsLoaiNhanVien){
            cmbLoaiNhanVien.addItem(lnv.getTenLoaiNhanVien());
             cmbTimLoaiNhanVien.addItem(lnv.getTenLoaiNhanVien());
        }
        
    }
    private void jButton10deleteNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10deleteNhanVienActionPerformed
        // TODO add your handling code here:
        int r = jTableNhanVien.getSelectedRow();
		if (r == -1)
			JOptionPane.showMessageDialog(this, "Chọn dòng cần xoá");
		else {
			if (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xoá?", "Cảnh báo",
					JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                             if(nvdao.deleteNhanVien(MaNhanVien.getText())){
                               
				modalNhanVien.removeRow(r); 
                                JOptionPane.showMessageDialog(null,"Xóa thành công");
                                
                                 MaNhanVien.setText("");
            txtTenNhanVien.setText("");
            checkBoxGioiTinh.setSelected(false);
            txtSDT.setText("");
            TextDiaChi.setText("");
            //TextNgaySinh.set(jTableNhanVien.getValueAt(row, 5).toString());
            txtCCCD.setText("");
            cmbLoaiNhanVien.setSelectedItem("");
            try{
             
                TextNgaySinh.setDate(null);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(TextNgaySinh, e);
            }            
        }
           else{
              JOptionPane.showMessageDialog(null,"Xóa thất bại ");
        }
			}
		}
    }//GEN-LAST:event_jButton10deleteNhanVienActionPerformed

    private void jbuttonThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonThemNhanVienActionPerformed
         nvdao=new NhanVienDao();
         
         MaNhanVien.setText(nvdao.TaoSoNgauNhien());
         String maNhanVien=MaNhanVien.getText();
         if(txtTenNhanVien.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Tên nhân viên không được để trống ");
             return ;
         }
         
         if(TextDiaChi.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Địa chỉ  nhân viên không được để trống ");
             return ;
         }
         
         if(txtCCCD.getText().equals("")){
             JOptionPane.showMessageDialog(null, "CCCD nhân viên không được để trống ");
             return ;
         }
         
         if(TextNgaySinh.getDate()==null){
             JOptionPane.showMessageDialog(null, "Ngày sinh  nhân viên không được để trống ");
             return ;
         }
         
         String TenNhanVien=txtTenNhanVien.getText();
         Boolean GioiTinh=checkBoxGioiTinh.isSelected()?true:false;
         String soDienThoai=txtSDT.getText();
         String diaChi=TextDiaChi.getText();
         String cccd=txtCCCD.getText();
         String LoaiNhanVien=cmbLoaiNhanVien.getSelectedItem().toString();
         Boolean trangThaiLamViec=cmbTrangThaiLamViec.getSelectedItem().toString().equalsIgnoreCase("Đang làm")?true:false;
         LoaiNhanVien lnv=new LoaiNhanVien(LoaiNhanVien.equalsIgnoreCase("Nhân viên thu ngân")?"LNV02":"LNV01", LoaiNhanVien);
         DateFormat dateFormat = null;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dateNgaySinh=sdf.format(TextNgaySinh.getDate());
         
         NhanVien nv=new NhanVien(maNhanVien, TenNhanVien, cccd, diaChi, soDienThoai, LoaiNhanVien, LocalDate.parse(dateNgaySinh) , GioiTinh, trangThaiLamViec, lnv);
         nvdao=new NhanVienDao();
        if (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn Thêm nhân viên  không ?", "Cảnh báo",
					JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
             if(nvdao.ThemNhanVien(nv)){
            	 modalNhanVien.addRow(new Object[]{nv.getMaNhanVien(),nv.getTenNhanVien(),nv.getGioiTinh()==true?"Nữ":"Nam",nv.getSoDienThoai(),nv.getDiaChi(),nv.getNgaySinh(),nv.getCCCD(),nv.getLnv().getTenLoaiNhanVien(),nv.getTrangThaiLamViec()? "Đang làm" : "Đã nghỉ" });    
           JOptionPane.showMessageDialog(null, "Thêm Nhân Viên Thành Công");
           
            MaNhanVien.setText("");
            txtTenNhanVien.setText("");
            checkBoxGioiTinh.setSelected(false);
            txtSDT.setText("");
            TextDiaChi.setText("");
            //TextNgaySinh.set(jTableNhanVien.getValueAt(row, 5).toString());
            txtCCCD.setText("");
            cmbLoaiNhanVien.setSelectedItem("");
            try{
             
                TextNgaySinh.setDate(null);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(TextNgaySinh, e);
            }            
            
        }
        else{
           JOptionPane.showMessageDialog(null, "Thêm Nhân Viên thất bại");
       }
        
        }
       
             
    }//GEN-LAST:event_jbuttonThemNhanVienActionPerformed

    private void jTableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNhanVienMouseClicked
      
            // TODO add your handling code here:
            int row = jTableNhanVien.getSelectedRow();
            MaNhanVien.setText(jTableNhanVien.getValueAt(row, 0).toString());
            txtTenNhanVien.setText(jTableNhanVien.getValueAt(row, 1).toString());
            checkBoxGioiTinh.setSelected(jTableNhanVien.getValueAt(row, 2).toString() == "Nữ" ? true : false);
            txtSDT.setText(jTableNhanVien.getValueAt(row, 3).toString());
            TextDiaChi.setText(jTableNhanVien.getValueAt(row, 4).toString());
            
            txtCCCD.setText(jTableNhanVien.getValueAt(row, 6).toString());
            cmbLoaiNhanVien.setSelectedItem(jTableNhanVien.getValueAt(row, 7).toString());
            cmbTrangThaiLamViec.setSelectedItem(jTableNhanVien.getValueAt(row, 8).toString());
            try{
                String ngayTale=jTableNhanVien.getValueAt(row, 5).toString();
                Date sdf=new SimpleDateFormat("yyyy-MM-dd").parse((String)ngayTale);
                TextNgaySinh.setDate(sdf);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(TextNgaySinh, e);
            }            
    }//GEN-LAST:event_jTableNhanVienMouseClicked
     
    private boolean kiemTraTen(){
        String cmnd=txtTenNhanVien.getText();
        if(cmnd.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(txtTenNhanVien, "Nhập tên để tìm nhân viên ");
             txtTenNhanVien.requestFocus();
            return false;
        }
            return true;
    }
    
    private void jButton3TimTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3TimTheoTenActionPerformed
        // TODO add your handling code here:
        if(kiemTraTen()){
            nvdao=new NhanVienDao();
            modalNhanVien=(DefaultTableModel)jTableNhanVien.getModel();
            ArrayList<NhanVien> dsNhanVien=(ArrayList<NhanVien>) nvdao.getNVByTen(txtTenNhanVien.getText());
            	modalNhanVien.getDataVector().removeAllElements();
            if (dsNhanVien.size() == 0) {
			JOptionPane.showMessageDialog(this, "Không có nhân viên này");
			return;
		}
            else{
            for(NhanVien nv:dsNhanVien){
                modalNhanVien.addRow(new Object[]{nv.getMaNhanVien(),nv.getTenNhanVien(),nv.getGioiTinh()==true?"Nữ":"Nam",nv.getSoDienThoai(),nv.getDiaChi(),nv.getNgaySinh(),nv.getCCCD(),nv.getLnv().getTenLoaiNhanVien(),nv.getTrangThaiLamViec()? "Đang làm" : "Đã nghỉ" });
             }
            }
        }
    }//GEN-LAST:event_jButton3TimTheoTenActionPerformed

    private void JbuttonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonLamMoiActionPerformed
        // TODO add your handling code here:
            MaNhanVien.setText("");
            txtTenNhanVien.setText("");
            checkBoxGioiTinh.setSelected(false);
            txtSDT.setText("");
            TextDiaChi.setText("");
            //TextNgaySinh.set(jTableNhanVien.getValueAt(row, 5).toString());
            txtCCCD.setText("");
            cmbLoaiNhanVien.setSelectedItem("");
            try{
             
                TextNgaySinh.setDate(null);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(TextNgaySinh, e);
            }            
    }//GEN-LAST:event_JbuttonLamMoiActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseExited

    private void jButton2UpdateNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2UpdateNhanVienActionPerformed
         
          int r = jTableNhanVien.getSelectedRow();
		if (r == -1)
	   JOptionPane.showMessageDialog(this, "Chọn dòng cần update ");
		else {
			if (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn uodate không ?", "Cảnh báo",
					JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                            try {
                                nvdao=new NhanVienDao();
                                String maNhanVien=MaNhanVien.getText();
                                String TenNhanVien=txtTenNhanVien.getText();
                                Boolean GioiTinh=checkBoxGioiTinh.isSelected()?true:false;
                                String soDienThoai=txtSDT.getText();
                                String diaChi=TextDiaChi.getText();
                                String cccd=txtCCCD.getText();
                                String loaiNhanVien=cmbLoaiNhanVien.getSelectedItem().toString();
                                Boolean trangThaiLamViec=cmbTrangThaiLamViec.getSelectedItem().toString().equalsIgnoreCase("Đang làm")?true:false;
                                LoaiNhanVien lnv=new LoaiNhanVien(loaiNhanVien=="Nhân viên thu ngân"?"LNV02":"LNV01", loaiNhanVien);
                                DateFormat dateFormat = null;
                                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                                String dateNgaySinh=sdf.format(TextNgaySinh.getDate());
                                NhanVien nv=new NhanVien(maNhanVien, TenNhanVien, cccd, diaChi, soDienThoai, loaiNhanVien, LocalDate.parse(dateNgaySinh) , GioiTinh, trangThaiLamViec, lnv);
                                if(nvdao.updateNV(nv)){
                                    modalNhanVien.setValueAt(txtTenNhanVien.getText(), r, 1);
                                    modalNhanVien.setValueAt(checkBoxGioiTinh.isSelected()?"Nữ":"Nam", r, 2);
                                    modalNhanVien.setValueAt(txtSDT.getText(), r, 3);
                                    modalNhanVien.setValueAt(TextDiaChi.getText(), r, 4);
                                    modalNhanVien.setValueAt(sdf.format(TextNgaySinh.getDate()), r, 5);
                                    modalNhanVien.setValueAt(txtCCCD.getText(), r, 6);
                                    modalNhanVien.setValueAt(cmbLoaiNhanVien.getSelectedItem().toString(), r, 7);
                                    modalNhanVien.setValueAt(cmbTrangThaiLamViec.getSelectedItem().toString(), r, 8);
                                    JOptionPane.showMessageDialog(null,"Update thành công");
                                    MaNhanVien.setText("");
                                    txtTenNhanVien.setText("");
                                    checkBoxGioiTinh.setSelected(false);
                                    txtSDT.setText("");
                                    TextDiaChi.setText("");
                                    //TextNgaySinh.set(jTableNhanVien.getValueAt(row, 5).toString());
                                    txtCCCD.setText("");
                                    cmbLoaiNhanVien.setSelectedItem("");
                                    try{
                                        TextNgaySinh.setDate(null);
                                    }
                                    catch(Exception e){
                                        JOptionPane.showMessageDialog(TextNgaySinh, e);
                                    }            
                                }
                                else{
                                    JOptionPane.showMessageDialog(null,"Update thất bại ");
                                }                   } catch (SQLException ex) {
                                Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
                            }
			}
		}
    }//GEN-LAST:event_jButton2UpdateNhanVienActionPerformed

    private void LocNhanVineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocNhanVineActionPerformed
        try {
            // TODO add your handling code here:
            String loaiNhanVien=cmbTimLoaiNhanVien.getSelectedItem().toString().equalsIgnoreCase("Quản lý nhân viên")?"LNV01":"LNV02";
            Boolean trangThaiLamViec=cmbTrangThaiLamViec.getSelectedItem().toString().equalsIgnoreCase("Đang làm")?true:false;
            ArrayList<NhanVien> listNhanVien=(ArrayList<NhanVien>) nvdao.LocNhanVien(loaiNhanVien, trangThaiLamViec);
            modalNhanVien.getDataVector().removeAllElements();
            if (listNhanVien.size() == 0) {
                JOptionPane.showMessageDialog(this, "Không có nhân viên này");
                return;
            }
            else{
                for(NhanVien nv:listNhanVien){
                    modalNhanVien.addRow(new Object[]{nv.getMaNhanVien(),nv.getTenNhanVien(),nv.getGioiTinh()==true?"Nữ":"Nam",nv.getSoDienThoai(),nv.getDiaChi(),nv.getNgaySinh(),nv.getCCCD(),nv.getLnv().getTenLoaiNhanVien(),nv.getTrangThaiLamViec()? "Đang làm" : "Đã nghỉ" });
                   
                }
                 JOptionPane.showMessageDialog(this, "Lọc thành công "); 
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LocNhanVineActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int r = jTableNhanVien.getSelectedRow();
		if (r == -1)
                {
	           JOptionPane.showMessageDialog(this, "Chọn nhân viên cần tạo tài khoản");
                }
		else {
                        ArrayList<NhanVien> dsNhanVien=nvdao.getAllNhanVien();
                         ArrayList<TaiKhoan> dsTaiKhoan=nvdao.getAllTaiKhoangNhanVien();
                        
                        
                               for(TaiKhoan tk:dsTaiKhoan){
                                   if(MaNhanVien.getText().trim().equals(tk.getMaNhanvien().trim())){
                                       
                                        JOptionPane.showMessageDialog(this, "Tài Khoản nhân viên đã được tạo vui lòng chọn nhân viên khác ");
                                        return ;
                                }           
                                 }
                         
                           if (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn tạo tài khoản không?", "Cảnh báo",
					JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                            form_register=new Form_Register();
                                            form_register.setVisible(true);
                                            form_register.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                                            form_register.MaNhanVienDefault.setText(MaNhanVien.getText());
                                            form_register.MataiKhoang.setText(nvdao.TaoMaTaiKhoanNgauNhien());
                                            form_register.jLabel3UserNameNhanVien.setText(MaNhanVien.getText());
                                      }
                } 
    }//GEN-LAST:event_jButton9ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbuttonLamMoi;
    private javax.swing.JButton LocNhanVine;
    private javax.swing.JLabel MaNhanVien;
    private javax.swing.JTextField TextDiaChi;
    private com.toedter.calendar.JDateChooser TextNgaySinh;
    private javax.swing.JCheckBox checkBoxGioiTinh;
    private javax.swing.JComboBox<String> cmbLoaiNhanVien;
    private javax.swing.JComboBox<String> cmbTimLoaiNhanVien;
    private javax.swing.JComboBox<String> cmbTimTrangThaiLamViec;
    private javax.swing.JComboBox<String> cmbTrangThaiLamViec;
    private javax.swing.JButton jButton10deleteNhanVien;
    private javax.swing.JButton jButton2UpdateNhanVien;
    private javax.swing.JButton jButton3TimTheoTen;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNhanVien;
    private javax.swing.JButton jbuttonThemNhanVien;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables
}
